'use client'

import Link from 'next/link'
import { motion } from 'framer-motion'
import { ArrowUpRight, BrainCircuit, HeartPulse, Network, ShieldCheck, Signal, Sparkles } from 'lucide-react'

const systems = [
  ['Internet', 'OFFLINE', 'red'], ['Satellites', 'OFFLINE', 'red'], ['Cellular', 'OFFLINE', 'red'], ['PHOENIX MESH', 'ONLINE', 'green'],
]
const modules = [
  ['Knowledge Capsules', 'Structured, verified reports—not noisy messages.', '01'], ['Adaptive Language', 'A communication protocol that changes before it can be decoded.', '02'], ['Trust Network', 'Confidence built through nearby people, doctors and community leaders.', '03'], ['AI Intelligence', 'Signals become priorities, predictions and safe next actions.', '04'], ['Resource Exchange', 'Available meets required—matched across the community.', '05'], ['Situation Map', 'The offline map for food, medicine, shelter, rescue and danger.', '06'],
]

function NetworkField() { return <div className="absolute inset-0 overflow-hidden opacity-70"><div className="radar" />{Array.from({length: 16}, (_,i) => <i key={i} className="node" style={{left: `${8 + (i * 29) % 84}%`, top: `${10 + (i * 47) % 76}%`, animationDelay: `${i * -.42}s`}} />)}<svg className="absolute inset-0 h-full w-full"><path d="M8 80 Q190 20 345 115 T650 55 T1000 150" fill="none" stroke="rgba(34,211,238,.36)" strokeWidth="1" strokeDasharray="5 12" className="flow-line"/><path d="M15 310 Q230 135 500 280 T1100 205" fill="none" stroke="rgba(251,146,60,.24)" strokeWidth="1" strokeDasharray="3 14" className="flow-line"/></svg></div> }

export default function LandingPage() { return <div className="min-h-screen overflow-hidden bg-[#050b16] text-slate-100">
  <nav className="relative z-10 mx-auto flex max-w-[1480px] items-center justify-between px-5 py-5 lg:px-8"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl border border-cyan-300/50 bg-cyan-300/10"><Signal className="text-cyan-200" /></span><b className="tracking-[.32em] text-cyan-100">PHOENIX</b></div><div className="flex gap-3"><Link href="/about" className="hidden px-4 py-2 text-sm text-slate-400 sm:block">Why Phoenix</Link><Link href="/dashboard" className="phoenix-button text-sm">Enter command center <ArrowUpRight className="inline h-4 w-4" /></Link></div></nav>
  <section className="relative isolate min-h-[760px] border-y border-cyan-300/10"><NetworkField /><div className="relative z-[2] mx-auto grid max-w-[1480px] gap-12 px-5 pb-20 pt-20 lg:grid-cols-[1.1fr_.9fr] lg:px-8 lg:pt-32"><motion.div initial={{opacity:0,y:22}} animate={{opacity:1,y:0}} transition={{duration:.8}}><p className="mb-5 flex items-center gap-2 text-xs font-bold tracking-[.28em] text-orange-300"><Sparkles className="h-4 w-4" /> FIRST CONTACT PROTOCOL // ACTIVE</p><h1 className="max-w-4xl text-5xl font-black leading-[.96] tracking-tight text-white md:text-7xl xl:text-8xl">Rebuilding human <span className="text-cyan-300">communication</span> after first contact.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-400">“When every known communication system failed, humanity created a new one.” Phoenix is an AI-assisted civilization operating system for communication, coordination, trust and resource management.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/dashboard" className="phoenix-button px-6 py-3">Launch live demo <ArrowUpRight className="inline h-4 w-4" /></Link><Link href="/language" className="phoenix-button-outline px-6 py-3">Explore adaptive language</Link></div></motion.div>
  <motion.div initial={{opacity:0,scale:.94}} animate={{opacity:1,scale:1}} transition={{delay:.25}} className="mission-card self-center p-5"><div className="mb-5 flex items-center justify-between"><p className="label">GLOBAL COMMS STATUS</p><span className="text-[10px] text-cyan-300">LIVE / 09:41:18</span></div><div className="space-y-3">{systems.map(([label,status,color],i) => <motion.div key={label} initial={{x:24,opacity:0}} animate={{x:0,opacity:1}} transition={{delay:.4+i*.1}} className="flex items-center justify-between border-b border-white/5 pb-3"><span className="text-sm text-slate-300">{label}</span><span className={`status ${color}`}>{status}</span></motion.div>)}</div><div className="mt-6 rounded-lg border border-cyan-300/15 bg-cyan-300/5 p-4"><div className="flex items-center gap-3"><Network className="h-8 w-8 text-cyan-300"/><div><b className="text-sm">12,847 mesh nodes relaying</b><p className="mt-1 text-xs text-slate-500">Human → Nearby Humans → Community → Civilization</p></div></div></div></motion.div></div></section>
  <section className="mx-auto max-w-[1480px] px-5 py-24 lg:px-8"><div className="mb-12 flex flex-wrap items-end justify-between gap-6"><div><p className="label">THE OPERATING SYSTEM</p><h2 className="mt-3 text-4xl font-bold md:text-5xl">Not another messaging app.</h2></div><p className="max-w-md text-slate-400">Every signal becomes an actionable, locally stored, trusted unit of collective knowledge.</p></div><div className="grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 md:grid-cols-2 lg:grid-cols-3">{modules.map(([title,desc,num]) => <Link href={title === 'Adaptive Language' ? '/language' : '/dashboard'} key={title} className="group bg-[#08101e] p-7 transition hover:bg-cyan-300/10"><span className="text-xs text-orange-300">{num}</span><h3 className="mt-8 text-xl font-bold text-cyan-50 group-hover:text-cyan-300">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{desc}</p><ArrowUpRight className="mt-7 h-5 w-5 text-slate-500 transition group-hover:translate-x-1 group-hover:-translate-y-1 group-hover:text-cyan-300" /></Link>)}</div></section>
  <section className="border-y border-orange-300/15 bg-orange-300/[.03] px-5 py-16 text-center"><ShieldCheck className="mx-auto h-8 w-8 text-orange-300"/><h2 className="mx-auto mt-5 max-w-3xl text-3xl font-bold">Civilization does not wait for a signal. It becomes the signal.</h2><Link href="/dashboard" className="mt-7 inline-block text-sm font-bold text-cyan-300">OPEN THE COMMAND CENTER →</Link></section>
  <footer className="mx-auto flex max-w-[1480px] items-center justify-between px-5 py-8 text-[10px] tracking-widest text-slate-600 lg:px-8"><span>PHOENIX / LOCAL-FIRST / NO CLOUD REQUIRED</span><span>© 2026 HUMAN NETWORK</span></footer>
</div> }
